# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "fd2ba0c73278e95df5820128062a1de1be6f4cc4";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "fd2ba0c73278e95df5820128062a1de1be6f4cc4";
      fetchSubmodules = false;
      sha256 = "sha256-oniOTue8NvYx+ypjB/trJzYi1RCEH16AslLlzabsVFY=";
    };
    date = "2024-09-06";
  };
  chisel-interface = {
    pname = "chisel-interface";
    version = "9f42edc9d5ada43962fe65d3a2ed6db21763641a";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel-interface";
      rev = "9f42edc9d5ada43962fe65d3a2ed6db21763641a";
      fetchSubmodules = false;
      sha256 = "sha256-KbkXEDhv1MTj51/3e7EQEy9JCQ0mbbKu84hufVXmoEk=";
    };
    date = "2024-08-12";
  };
}
