# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "ecda00a58459055c219a982142e98c194666c339";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "ecda00a58459055c219a982142e98c194666c339";
      fetchSubmodules = false;
      sha256 = "sha256-6HKRSQgin3EJlt8dE0mJPZ+lSI8eTyRy3jj0cy9tGNQ=";
    };
    date = "2024-09-13";
  };
  chisel-interface = {
    pname = "chisel-interface";
    version = "9f42edc9d5ada43962fe65d3a2ed6db21763641a";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel-interface";
      rev = "9f42edc9d5ada43962fe65d3a2ed6db21763641a";
      fetchSubmodules = false;
      sha256 = "sha256-KbkXEDhv1MTj51/3e7EQEy9JCQ0mbbKu84hufVXmoEk=";
    };
    date = "2024-08-12";
  };
}
